### ISSUE TITLE
Enhancement:Low adaptability for OnePlus 7pro

### ISSUE THREAD

**Issue by Mingle-2012** [llipengda/voice-of-ecnu#63]
![Evidence](https://github.com/llipengda/voice-of-ecnu/assets/133673143/4f09ea4e-53b7-4984-abff-5bd3bf717cf0)
I found a problem on my phone while using the miniapp.

**Comment by Mingle-2012** [comment]
清楚缓存并重启小程序按钮换行了

**Comment by llipengda** [comment]
给我截个图

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
